site:
  title: KSODI POC Documentation
  url: 
  start_page: ROOT::index.adoc
  
content:
  sources:
    - url: ..
      start_path: docs
      branches: HEAD

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ../build

antora:
  extensions:
    - '@antora/lunr-extension'
